### ISSUE TITLE
DI components are not in good package organizing

### ISSUE THREAD

**Issue by luongvo** [silapinn/android-nimble-surveys#3]
Hi @silapinn , I'm Lucas from Nimble. Nice to meet you again here 👋 
I'll take care of reviewing your assignment and give you some feedback here from our side by opening issue tickets. Please feel free to catch up on this and help us know more about you by discussing and resolving the issues.

Firstly, you're doing well, the build is running smoothly and has a good ui 👌
But, when checking your code, there is something could be improved about DI components package organizing:
- Why do you keep `AuthorizationInterceptor`, `TokenAuthenticator` and `SharedPrefsHelper` in the root package?
- `BasePresenter` and `BaseView` belong to MVP architecture, should we keep them in `ui` package?
- In `AuthenticationRepository`, `getAccessToken` does 2 tasks: request new access token from api and save access token. I don't think that's good organizing. A get function should does returning data only.
- Since you kept `BASE_URL` in gradle config, that's good point, why did you still keep `DEFAULT_USERNAME` and `DEFAULT_PASSWORD` in `TokenAuthenticator`? 🤔

**Comment by silapinn** [comment]
@luongvo I have reorganized `AuthorizationInterceptor`, `TokenAuthenticator`, `SharedPrefsHelper`, `BaseView`, `BasePresenter` to be inside its proper package, moved saving access token out of the repository, put default username and password inside Gradle config, and created 2 PRs for these changes.

**Comment by luongvo** [comment]
@silapinn lgtm now, you can go ahead to merge PRs
